### PR TITLE
Use TaskCompletionListener to ensure ResultSet is always closed

### LINKED ISSUE #395: Direct Memory Allocation Failure on Spark 3.1.2 when using arrow
I am using the following versions of spark-snowflake on Spark 3.1.2 ([Databricks Runtime Version 9.1](https://docs.databricks.com/release-notes/runtime/9.1.html)) 

snowflake-ingest-sdk-0.10.2.jar
snowflake-jdbc-3.13.3.jar
spark-snowflake_2.12-2.9.0-spark_3.1.jar

Exception:
```
21/11/17` 21:09:52 INFO SnowflakeTelemetry$: Send OOB Telemetry message: ResultIterator read
21/11/17 21:09:52 ERROR Executor: Exception in task 33.0 in stage 9021.0 (TID 137818)
net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver internal error: Max retry reached for the download of #chunk0 (Total chunks: 13) retry=10, error=net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver internal error: Exception: Failure allocating buffer..
	at net.snowflake.client.jdbc.SnowflakeChunkDownloader$2.downloadAndParseChunk(SnowflakeChunkDownloader.java:806)
	at net.snowflake.client.jdbc.SnowflakeChunkDownloader$2.call(SnowflakeChunkDownloader.java:861)
	at net.snowflake.client.jdbc.SnowflakeChunkDownloader$2.call(SnowflakeChunkDownloader.java:772)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.snowflake.client.jdbc.internal.apache.arrow.memory.OutOfMemoryException: Failure allocating buffer.
	at net.snowflake.client.jdbc.internal.io.netty.buffer.PooledByteBufAllocatorL.allocate(PooledByteBufAllocatorL.java:60)
	at net.snowflake.client.jdbc.internal.apache.arrow.memory.AllocationManager.<init>(AllocationManager.java:78)
	at net.snowflake.client.jdbc.internal.apache.arrow.memory.BaseAllocator.bufferWithoutReservation(BaseAllocator.java:347)
	at net.snowflake.client.jdbc.internal.apache.arrow.memory.BaseAllocator.buffer(BaseAllocator.java:315)
	at net.snowflake.client.jdbc.internal.apache.arrow.memory.BaseAllocator.buffer(BaseAllocator.java:279)
	at net.snowflake.client.jdbc.internal.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:695)
	at net.snowflake.client.jdbc.internal.apache.arrow.vector.ipc.message.MessageChannelReader.readNext(MessageChannelReader.java:68)
	at net.snowflake.client.jdbc.internal.apache.arrow.vector.ipc.ArrowStreamReader.loadNextBatch(ArrowStreamReader.java:106)
	at net.snowflake.client.jdbc.ArrowResultChunk.readArrowStream(ArrowResultChunk.java:78)
	at net.snowflake.client.jdbc.SnowflakeChunkDownloader$2.downloadAndParseChunk(SnowflakeChunkDownloader.java:790)
	... 6 more
Caused by: net.snowflake.client.jdbc.internal.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 43822088192, max: 43822088192)
	at net.snowflake.client.jdbc.internal.io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at net.snowflake.client.jdbc.internal.io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at net.snowflake.client.jdbc.internal.io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at net.snowflake.client.jdbc.internal.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at net.snowflake.client.jdbc.internal.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at net.snowflake.client.jdbc.internal.io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
	at net.snowflake.client.jdbc.internal.io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at net.snowflake.client.jdbc.internal.io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.newDirectBufferL(PooledByteBufAllocatorL.java:173)
	at net.snowflake.client.jdbc.internal.io.netty.buffer.PooledByteBufAllocatorL$InnerAllocator.directBuffer(PooledByteBufAllocatorL.java:206)
	at net.snowflake.client.jdbc.internal.io.netty.buffer.PooledByteBufAllocatorL.allocate(PooledByteBufAllocatorL.java:58)
	... 15 more
.
	at net.snowflake.client.jdbc.SnowflakeChunkDownloader.getNextChunkToConsume(SnowflakeChunkDownloader.java:510)
	at net.snowflake.client.core.SFArrowResultSet.fetchNextRowUnsorted(SFArrowResultSet.java:233)
	at net.snowflake.client.core.SFArrowResultSet.fetchNextRow(SFArrowResultSet.java:210)
	at net.snowflake.client.core.SFArrowResultSet.next(SFArrowResultSet.java:346)
	at net.snowflake.client.jdbc.SnowflakeResultSetV1.next(SnowflakeResultSetV1.java:99)
	at net.snowflake.spark.snowflake.io.ResultIterator.hasNext(SnowflakeResultSetRDD.scala:142)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$3(ShuffleMapTask.scala:81)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ShuffleMapTask.$anonfun$runTask$1(ShuffleMapTask.scala:81)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:150)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:119)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:91)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:813)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1605)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:816)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:672)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
21/11/17 21:09:52 INFO CoarseGrainedExecutorBackend: Got assigned task 138546
```

Setting use_copy_unload=true fixes the issue. Any ideas on why snowflake-spark-connector is consuming ~43GB of direct memory? It doesn't seem like an issue on Spark 3.1.1

### LINKED ISSUE #397: ResultIterator may fail to close ResultSet in case Spark task fails or does not consume entire iterator
I think that I've spotted a potential resource leak in `ResultIterator`: currently, I think it it only closes the underlying `ResultSet` when `hasNext` is called and returns `false` (see [code](https://github.com/snowflakedb/spark-snowflake/blob/663c74ce4d6b5e433298cb02e1dbfb0c225699a2/src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala#L153-L154)).

However, there's a couple of circumstances where that call might not occur:

1. If the Spark task fails with an exception or is cancelled.
2. If the iterator is not fully iterated. One way that this could happen is if a per-partition limit operator is stacked on top of the Snowflake scan. 

To avoid this class of problem, I recommend that ResultIterator registers a TaskCompletionListener to ensure that `data.close()` is called upon task completion. Here's an example of this pattern in Spark's built-in JDBC Datasource: https://github.com/apache/spark/blame/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JDBCRDD.scala#L321

This assumes that `close()` is idempotent (or can be made idempotent with a `if(!isClosed)` check in `ResultIterator`).

I suspect (but have not confirmed) that this problem might be a contributing factor to the `OutOfDirectMemoryError`s reported in #395: if the `ResultSet` is garbage collected without being closed then I'm worried that Arrow-allocated memory will be leaked.

### PR DESCRIPTION
**Pull request by JoshRosen**
This PR fixes a direct/off-heap memory leak in `ResultIterator`. 

In the current code, the underlying `ResultSet` is only closed when `hasNext` is called and returns `false`. However, there are a few situations where that call might not occur:

1. If the Spark task fails with an exception or is cancelled.
2. If the iterator is not fully iterated. One way that this could happen is if a per-partition limit operator is stacked on top of the Snowflake scan.

Failing to close the `ResultSet` can cause direct/off-heap memory to be leaked (if the Arrow-based ResultSet implementation is being used).

This PR fixes that issue by modifying the code to register a `TaskCompletionListener` to ensure that `data.close()` is called upon task completion or failure. A similar pattern is used in Spark's built-in JDBC datasource: https://github.com/apache/spark/blame/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JDBCRDD.scala#L321 . I used a private `closeResultSet()` helper method to ensure that the `close()` call is idempotent.

**Testing**: I discovered this problem while investigating an issue reported by a Databricks customer. We confirmed that this fix resolved the memory leak.

I don't have a Snowflake account and therefore haven't added an end-to-end integration test to act as a regression test for this bug.

Fixes #397.
Fixes #395.

### CODE REVIEW

File: src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala [hunk 1]
```diff
@@ -125,9 +127,19 @@ case class ResultIterator[T: ClassTag](
     }
   }
 
+  context.addTaskCompletionListener[Unit](_ => closeResultSet())
+
   val isIR: Boolean = isInternalRow[T]
   val mapper: ObjectMapper = new ObjectMapper()
   var currentRowNotConsumedYet: Boolean = false
+  var resultSetIsClosed: Boolean = false
```
Comment (sfc-gh-mrui) [inline src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala:135]: It will be better to declare `var resultSetIsClosed: Boolean = false` before `addTaskCompletionListener()`.

File: src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala [hunk 2]
```diff
@@ -125,9 +127,19 @@ case class ResultIterator[T: ClassTag](
     }
   }
 
+  context.addTaskCompletionListener[Unit](_ => closeResultSet())
```
Comment (sfc-gh-mrui) [inline src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala:130]: Can we avoid introduce `context` by using `TaskContext.get()`?
`TaskContext.get().addTaskCompletionListener[Unit](_ => closeResultSet())`

File: src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala [hunk 3]
```diff
@@ -125,9 +127,19 @@ case class ResultIterator[T: ClassTag](
...
   val isIR: Boolean = isInternalRow[T]
   val mapper: ObjectMapper = new ObjectMapper()
   var currentRowNotConsumedYet: Boolean = false
+  var resultSetIsClosed: Boolean = false
+
+  private def closeResultSet(): Unit = {
+    if (!resultSetIsClosed) {
+      data.close()
+      resultSetIsClosed = true
+    }
```
Comment (sfc-gh-mrui) [inline src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala:141]:
```
      resultSetIsClosed = true
      data.close()
```

Comment (sfc-gh-mrui) [reply src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala:141]: @JoshRosen Appreciated so much for your contributions! Left some comments.

Comment (JoshRosen) [reply src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala:139]: @sfc-gh-mrui, I've pushed a commit addressing this round of comments.

File: src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala (hunk 1 above)
Comment (JoshRosen) [reply src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala:131]: I moved the `addTaskCompletionListener` down a couple of lines.

**Review by sfc-gh-mrui — APPROVED** [review]
LGTM.
I will ask other team remembers to take a look.

**Review by sfc-gh-ema — APPROVED** [review]
LGTM.

**Review by sfc-gh-bli — APPROVED** [review]
LGTM

**Comment by sfc-gh-mrui** [comment]
I have kicked off a precommit test for this PR. It is passed. https://github.com/snowflakedb/spark-snowflake/pull/401
